version: '3.9'
services:
  my-db:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: file-upload
    ports:
      - "5432:5432"
volumes:  
 postres:
